## Installation Instructions

      conda install numpy
   

In [ ]:
#pip install numpy

In [1]:
import numpy as np

# Numpy Arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
test1 = [12,12,13,15]
test1

[12, 12, 13, 15]

In [3]:
test2 = [22,18,15,30]
test2

[22, 18, 15, 30]

In [4]:
test1 + test2

[12, 12, 13, 15, 22, 18, 15, 30]

In [5]:
T1 = np.array(test1)
print(T1)
T2 = np.array(test2)
print(T2)

[12 12 13 15]
[22 18 15 30]


In [6]:
print(type(test1))
print(type(T1))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
T1 + T2

array([34, 30, 28, 45])

In [10]:
#T1 = np.array([2,3,5,8])
#T2 = np.array([10,15,12])
#T1 + T2

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
type(my_matrix)

list

In [16]:
np.array([test1, test2])

array([[12, 12, 13, 15],
       [22, 18, 15, 30]])

## Built-in Methods

### arange

Return evenly spaced values within a given interval.

In [20]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
list(range(5,15,1))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [28]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [1]:
#list(range(0,1,0.1))
#list(range(10,5,-1))

In [32]:
#-3 to 3 0.01
np.arange(-3,3,0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [33]:
np.arange(3,-3,-0.5)

array([ 3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5, -2. ,
       -2.5])

### zeros and ones

Generate arrays of zeros or ones

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [42]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [44]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
#np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

In [46]:
#np.arange(0,1.01,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## eye

Creates an identity matrix

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [61]:
np.random.rand(5)

array([0.20426937, 0.8903512 , 0.59242477, 0.8979251 , 0.40186133])

In [62]:
np.random.rand(3,2)

array([[0.89746693, 0.77343035],
       [0.69586619, 0.66024845],
       [0.93801739, 0.60500872]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [63]:
np.random.randn(5)

array([-0.88548025,  0.1456235 , -0.11496655, -0.15750636,  0.57137434])

In [80]:
np.random.randn(3,3)

array([[ 0.57209465,  0.38117571,  0.95499634],
       [ 2.15308979, -0.17534041, -0.60670671],
       [-1.72209838, -0.61534365, -0.8280745 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [92]:
np.random.randint(1,100)

38

In [90]:
np.random.randint(1,100,5)

array([13, 59, 27,  1, 22])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [93]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,12)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
ranarr

array([23,  5, 38, 40, 26, 43, 28,  4, 32, 15,  6, 42])

## Reshape
Returns an array containing the same data with a new shape.

In [101]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
ranarr.reshape(2,3,2)

array([[[23,  5],
        [38, 40],
        [26, 43]],

       [[28,  4],
        [32, 15],
        [ 6, 42]]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [109]:
ranarr

array([23,  5, 38, 40, 26, 43, 28,  4, 32, 15,  6, 42])

In [111]:
ranarr.max()

43

In [113]:
ranarr.argmax()

5

In [118]:
#np.array([2,21,21,5,3,8,18]).argmin()
#[2,21,21,5,3,8,18].min()
max([2,21,21,5,3,8,18])

21

In [119]:
ranarr.min()

4

In [120]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [121]:
# Vector
arr.shape

(25,)

In [122]:
type(arr.shape)

tuple

In [123]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [124]:
arr.reshape(1,25).shape

(1, 25)

In [125]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [126]:
arr.reshape(25,1).shape

(25, 1)

In [127]:
x=ranarr.reshape(2,6)
x

array([[23,  5, 38, 40, 26, 43],
       [28,  4, 32, 15,  6, 42]])

In [131]:
x.shape

(2, 6)

In [132]:
print("No. of rows=",x.shape[0]) # No. of rows
print("No. of columns=",x.shape[1]) # No. of columns

No. of rows= 2
No. of columns= 6


### dtype

You can also grab the data type of the object in the array:

In [133]:
ranarr.dtype

dtype('int32')

In [134]:
np.random.rand(5).dtype

dtype('float64')

In [137]:
#[5]*7
#np.repeat(5,7)
list(range(10,90,5))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85]

In [140]:
np.repeat(12,9).reshape(3,3)#.shape

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [142]:
np.zeros((3,3))+12

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]])

In [144]:
np.ones((3,3))*12

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]])

In [145]:
np.full((3,3),12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [146]:
np.repeat(12,9).reshape(3,3)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [ ]:
arr.reshape(5,5)

In [147]:
Y=np.matrix(arr.reshape(5,5))

In [148]:
Y

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [149]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])