# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(2,15)

In [3]:
#Show
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
#Get a value at an index
arr[8]

10

In [7]:
#Get values in a range
arr[0:5]

array([2, 3, 4, 5, 6])

In [9]:
#Get values in a range
arr[8:]

array([10, 11, 12, 13, 14])

In [10]:
arr[[5,10,2,0]]

array([ 7, 12,  4,  2])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
#Setting a value with index range (Broadcasting)
arr[0:5]=15
#Show
arr

array([15, 15, 15, 15, 15,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#Important notes on Slices
slice_of_arr = arr[0:6]
#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
#Change Slice
slice_of_arr[:2]=50
#Show Slice again
slice_of_arr

array([50, 50,  2,  3,  4,  5])

Now note the changes also occur in our original array!

In [15]:
arr

array([50, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [16]:
#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy

array([50, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_copy[[1,3,5]] = 0
print(arr_copy)
print(arr)

[50  0  2  0  4  0  6  7  8  9 10]
[50 50  2  3  4  5  6  7  8  9 10]


## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d.shape

(3, 3)

In [20]:
arr_2d[1:,1:] 

array([[25, 30],
       [40, 45]])

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
#Indexing row
arr_2d[0]

array([ 5, 10, 15])

In [27]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[0][1]

10

In [28]:
# Getting individual element value
arr_2d[0,1]

10

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [34]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [35]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [38]:
arr_2d[:,1]

array([10, 25, 40])

### Fancy Indexing...

Fancy indexing allows you to select entire rows or columns out of order:

In [39]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
arr2d.shape

(10, 10)

In [41]:
#Length of array
#arr2d.shape
arr_length = arr2d.shape[1]
arr_length

10

In [43]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
list(range(arr_length))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
arr2d[8]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
for i in range(arr_length):
    print(i)
    print(arr2d[i])

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
9
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
#Set up array
for i in range(arr_length):
    arr2d[i]=i #arr2d[:,i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [56]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [57]:
arr2d[[2,4,6,8],0:5]

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [58]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [59]:
arr = np.random.randint(1,100,10)
arr

array([77, 45, 31, 58, 40, 53, 75, 57, 33, 42])

In [60]:
arr[8]

33

In [61]:
arr > 40

array([ True,  True, False,  True, False,  True,  True,  True, False,
        True])

In [63]:
bool_arr = arr > 40

In [64]:
bool_arr

array([ True,  True, False,  True, False,  True,  True,  True, False,
        True])

In [65]:
arr[bool_arr]

array([77, 45, 58, 53, 75, 57, 42])

In [66]:
arr[arr>40]

array([77, 45, 58, 53, 75, 57, 42])

In [67]:
x = 40
arr[arr>x]

array([77, 45, 58, 53, 75, 57, 42])

In [69]:
np.where(arr>40)[0]

array([0, 1, 3, 5, 6, 7, 9], dtype=int64)

In [70]:
arr[np.where(arr>40)[0]]

array([77, 45, 58, 53, 75, 57, 42])