In [ ]:
# with the help of numpy we create array in python
import numpy as np
my_arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
type(my_arr)

numpy.ndarray

In [ ]:
# generate random number
rand_num=np.random.randint(1,100,size=5)

In [ ]:
print(rand_num)

[ 2 82 30 34  9]


In [ ]:
# array shape manipulation
my_arr=np.array([10,15,11,13,14])
reshape_arr=my_arr.reshape(1,5)
print(reshape_arr)

[[10 15 11 13 14]]


In [ ]:
#array indexing
my_arr[2]

11

In [ ]:
#array operation
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
result=array1 + array2

In [ ]:
print(result)

[ 7  9 11 13 15]


In [ ]:
arr=np.array([12,15,17,18,19,20,30,35,50,23])

In [ ]:
c=arr[arr>30]

In [ ]:
print(c)

[35 50]


In [ ]:
arr1=np.array([1,2,3])
scalar=10
result=arr1 * scalar
print(result)

[10 20 30]


In [ ]:
mean=np.mean(my_arr)

In [ ]:
print(mean)

12.6
